# Generated by Django 5.1.4 on 2025-01-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destination_name',
            new_name='landmark',
        ),
    ]
