# Generated by Django 5.1.4 on 2025-01-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_api', '0002_rename_destination_name_destination_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourite_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='travel_planner_api.destination'),
        ),
    ]
