# Generated by Django 5.1.4 on 2025-01-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner_api', '0003_alter_customuser_favourite_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
